
all: atkin ecpp

atkin: atkin237.cpp
	g++ -I/opt/local/include -L/opt/local/lib -lgmpxx -lgmp -o atkin atkin237.cpp

ecpp: ecpp.cpp
	gcc -I/opt/local/include -L/opt/local/lib -lgmp -o ecpp ecpp.cpp

